.SILENT:

Test4:	Test4.cpp ImageNG.o Dimension.o MyQT.o
	echo "Création de Test4"
	g++ Test4.cpp -o Test4 MyQT.o ImageNG.o Dimension.o -lSDL -lpthread -Wl,-O1 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so

ImageNG.o:	ImageNG.cpp ImageNG.h
	echo "Création de ImageNG.o"
	g++ ImageNG.cpp -c -o ImageNG.o

Dimension.o:	Dimension.cpp Dimension.h
	echo "Création de Dimension.o"
	g++ Dimension.cpp -c -o Dimension.o

Couleur.o:	Couleur.cpp Couleur.h
	echo "Création de Couleur.o"
	g++ Couleur.cpp -c -o Couleur.o

MyQT.o:	MyQT.cpp MyQT.h
	echo "Création de MyQT.o"
	g++ MyQT.cpp -c -o MyQT.o -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++

clean:
	rm *.o

